#!/usr/bin/env bash
# bootstrap.sh — RitAPI Advanced one-liner installer
#
# Usage (recommended):
#   curl -sSL https://raw.githubusercontent.com/vadhh/ritapi-advanced/main/bootstrap.sh | bash
#
# Or clone first:
#   git clone https://github.com/vadhh/ritapi-advanced && cd ritapi-advanced && bash bootstrap.sh

set -euo pipefail

REPO_RAW="https://raw.githubusercontent.com/vadhh/ritapi-advanced/main"
COMPOSE_FILE="docker-compose.yml"
ENV_FILE=".env"
HEALTHZ_URL="http://localhost:8001/healthz"
HEALTH_RETRIES=20
HEALTH_WAIT=3

# ---------------------------------------------------------------------------
# Colours
# ---------------------------------------------------------------------------
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'

info()    { echo -e "${CYAN}▶ $*${NC}"; }
success() { echo -e "${GREEN}✓ $*${NC}"; }
warn()    { echo -e "${YELLOW}⚠ $*${NC}"; }
die()     { echo -e "${RED}✗ $*${NC}" >&2; exit 1; }

banner() {
    echo ""
    echo -e "${BOLD}${CYAN}╔══════════════════════════════════════════╗${NC}"
    echo -e "${BOLD}${CYAN}║      RitAPI Advanced — Bootstrap         ║${NC}"
    echo -e "${BOLD}${CYAN}╚══════════════════════════════════════════╝${NC}"
    echo ""
}

# ---------------------------------------------------------------------------
# Prereq checks
# ---------------------------------------------------------------------------
check_prereqs() {
    info "Checking prerequisites..."
    command -v docker >/dev/null 2>&1 || die "Docker is not installed. See https://docs.docker.com/get-docker/"

    # Compose v2 (plugin) or v1 (standalone)
    if docker compose version >/dev/null 2>&1; then
        COMPOSE_CMD="docker compose"
    elif command -v docker-compose >/dev/null 2>&1; then
        COMPOSE_CMD="docker-compose"
    else
        die "Docker Compose not found. Install the Docker Compose plugin: https://docs.docker.com/compose/install/"
    fi

    command -v curl >/dev/null 2>&1 || command -v wget >/dev/null 2>&1 || \
        die "curl or wget required."

    success "Prerequisites OK (using: $COMPOSE_CMD)"
}

# ---------------------------------------------------------------------------
# Download compose file if not already present
# ---------------------------------------------------------------------------
fetch_compose() {
    if [[ -f "$COMPOSE_FILE" ]]; then
        info "Found existing $COMPOSE_FILE — skipping download."
        return
    fi
    info "Downloading $COMPOSE_FILE..."
    if command -v curl >/dev/null 2>&1; then
        curl -fsSL "$REPO_RAW/$COMPOSE_FILE" -o "$COMPOSE_FILE"
    else
        wget -qO "$COMPOSE_FILE" "$REPO_RAW/$COMPOSE_FILE"
    fi
    success "Downloaded $COMPOSE_FILE"
}

# ---------------------------------------------------------------------------
# Generate a random hex secret
# ---------------------------------------------------------------------------
gen_secret() {
    if command -v openssl >/dev/null 2>&1; then
        openssl rand -hex 32
    else
        python3 -c "import secrets; print(secrets.token_hex(32))"
    fi
}

# ---------------------------------------------------------------------------
# Build .env interactively
# ---------------------------------------------------------------------------
configure_env() {
    if [[ -f "$ENV_FILE" ]]; then
        warn ".env already exists — skipping configuration."
        warn "Delete .env and re-run bootstrap.sh to reconfigure."
        return
    fi

    echo ""
    echo -e "${BOLD}Configuration${NC}"
    echo "────────────────────────────────────────────"
    echo "Press Enter to accept the auto-generated value."
    echo ""

    # SECRET_KEY
    DEFAULT_SECRET_KEY=$(gen_secret)
    read -rp "SECRET_KEY [auto]: " INPUT_SECRET_KEY
    SECRET_KEY="${INPUT_SECRET_KEY:-$DEFAULT_SECRET_KEY}"

    # ADMIN_SECRET
    DEFAULT_ADMIN_SECRET=$(gen_secret)
    read -rp "ADMIN_SECRET [auto]: " INPUT_ADMIN_SECRET
    ADMIN_SECRET="${INPUT_ADMIN_SECRET:-$DEFAULT_ADMIN_SECRET}"

    # REDIS_PASSWORD
    DEFAULT_REDIS_PASSWORD=$(gen_secret | cut -c1-24)
    read -rp "REDIS_PASSWORD [auto]: " INPUT_REDIS_PASSWORD
    REDIS_PASSWORD="${INPUT_REDIS_PASSWORD:-$DEFAULT_REDIS_PASSWORD}"

    # DASHBOARD_TOKEN (optional)
    read -rp "DASHBOARD_TOKEN (leave blank for open access): " DASHBOARD_TOKEN

    # PORT
    read -rp "Port to expose RitAPI on [8001]: " INPUT_PORT
    PORT="${INPUT_PORT:-8001}"

    cat > "$ENV_FILE" <<EOF
# RitAPI Advanced — generated by bootstrap.sh
# DO NOT commit this file to version control.

SECRET_KEY=${SECRET_KEY}
ADMIN_SECRET=${ADMIN_SECRET}
REDIS_PASSWORD=${REDIS_PASSWORD}
DASHBOARD_TOKEN=${DASHBOARD_TOKEN}

PORT=${PORT}
JWT_ALGORITHM=HS256
JWT_EXPIRE_MINUTES=60
RATE_LIMIT_REQUESTS=100
RATE_LIMIT_WINDOW=60
EOF

    success ".env written"
    echo ""
    warn "Save these credentials — they will NOT be shown again:"
    echo "  ADMIN_SECRET  = ${ADMIN_SECRET}"
    [[ -n "$DASHBOARD_TOKEN" ]] && echo "  DASHBOARD_TOKEN = ${DASHBOARD_TOKEN}"
    echo ""
}

# ---------------------------------------------------------------------------
# Pull latest image
# ---------------------------------------------------------------------------
pull_image() {
    info "Pulling latest RitAPI Advanced image..."
    $COMPOSE_CMD pull app
    success "Image pulled"
}

# ---------------------------------------------------------------------------
# Start services
# ---------------------------------------------------------------------------
start_services() {
    info "Starting services..."
    $COMPOSE_CMD up -d
    success "Services started"
}

# ---------------------------------------------------------------------------
# Wait for health check
# ---------------------------------------------------------------------------
wait_healthy() {
    info "Waiting for RitAPI Advanced to become healthy..."
    for i in $(seq 1 $HEALTH_RETRIES); do
        STATUS=$(curl -sf "$HEALTHZ_URL" 2>/dev/null | python3 -c "import sys,json; print(json.load(sys.stdin).get('status',''))" 2>/dev/null || true)
        if [[ "$STATUS" == "ok" ]]; then
            success "RitAPI Advanced is healthy"
            return
        fi
        echo -n "."
        sleep $HEALTH_WAIT
    done
    echo ""
    warn "Health check timed out. Check logs with: $COMPOSE_CMD logs app"
}

# ---------------------------------------------------------------------------
# Print completion summary
# ---------------------------------------------------------------------------
print_summary() {
    # Read back values from .env for display
    # shellcheck disable=SC1090
    source "$ENV_FILE" 2>/dev/null || true

    echo ""
    echo -e "${BOLD}${GREEN}╔══════════════════════════════════════════╗${NC}"
    echo -e "${BOLD}${GREEN}║        Installation complete! 🚀         ║${NC}"
    echo -e "${BOLD}${GREEN}╚══════════════════════════════════════════╝${NC}"
    echo ""
    echo -e "${BOLD}Endpoints${NC}"
    echo "  API      →  http://localhost:${PORT:-8001}"
    echo "  Health   →  http://localhost:${PORT:-8001}/healthz"
    echo "  Metrics  →  http://localhost:${PORT:-8001}/metrics"
    echo "  Docs     →  http://localhost:${PORT:-8001}/docs"
    echo "  Dashboard→  http://localhost:${PORT:-8001}/dashboard"
    echo ""
    echo -e "${BOLD}First steps${NC}"
    echo "  # Get an admin JWT:"
    echo "  curl -X POST http://localhost:${PORT:-8001}/admin/token \\"
    echo "    -H \"X-Admin-Secret: \$ADMIN_SECRET\""
    echo ""
    echo "  # Issue an API key:"
    echo "  curl -X POST http://localhost:${PORT:-8001}/admin/apikey \\"
    echo "    -H \"X-Admin-Secret: \$ADMIN_SECRET\" \\"
    echo "    -H \"Content-Type: application/json\" \\"
    echo "    -d '{\"subject\": \"myapp\", \"role\": \"VIEWER\"}'"
    echo ""
    echo -e "${BOLD}Useful commands${NC}"
    echo "  $COMPOSE_CMD logs -f app       # live logs"
    echo "  $COMPOSE_CMD ps                # service status"
    echo "  $COMPOSE_CMD down              # stop"
    echo "  $COMPOSE_CMD pull && $COMPOSE_CMD up -d   # upgrade"
    echo ""
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
banner
check_prereqs
fetch_compose
configure_env
pull_image
start_services
wait_healthy
print_summary
